#!/bin/sh

echo "Creating commit streak image"
PYTHON_ENV=$(python -c "import sys; sys.stdout.write('1') if hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix) else sys.stdout.write('0')")

if [ $PYTHON_ENV -eq 0 ]
then
  echo "Not in virtual env. Not going to try to create streak image"
  exit
fi

mkdir -p $PWD/media/

# Create the streak image
python $PWD/day_13/commit_streak_image_generator.py $PWD  $PWD/day_13/media $PWD/media/streak.jpg
git add $PWD/media/streak.jpg